import { Metadata } from "next";
import "@/assets/css/globals.css";
import { http } from "@/lib/http";
import { hasLocale } from "next-intl";
import { User } from "@/types/shared";
import { cookies } from "next/headers";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { Toaster } from "@/components/ui/sonner";
import { NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { Inter, Lora, Cairo } from "next/font/google";
import { ReferenceData } from "@/types/reference-data";
import { UserProvider } from "@/providers/user-provider";
import { DirectionProvider } from "@/components/ui/direction";
import { ReferenceDataProvider } from "@/providers/reference-data.provider";
import { NuqsAdapter } from "nuqs/adapters/next/app";

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Huqouq",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({ children, params }: Props) {
  const { locale } = await params;
  let user: User | null = null;
  const cookiesStore = await cookies();
  const token = cookiesStore.get("token")?.value;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);
  const dir = locale === "ar" ? "rtl" : "ltr";

  // Fetch the reference data from the API
  const { data: referenceData, ok: referenceDataOk } =
    await http.get<ReferenceData>("/api/reference-data");

  if (!referenceDataOk) {
    throw new Error("Failed to fetch reference data");
  }

  // Fetch the authenticated user's data if a token is present
  if (token) {
    const { data: userData, ok } = await http.get<{ data: User }>(
      "/api/auth/me",
    );

    if (!ok) {
      throw new Error("Failed to fetch user data");
    }

    user = userData.data;
  }

  return (
    <html
      lang={locale}
      dir={dir}
      className={`${inter.variable} ${lora.variable} ${cairo.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NuqsAdapter>
          <ReferenceDataProvider initialReferenceData={referenceData}>
            <UserProvider initialUser={user}>
              <NextIntlClientProvider>
                <DirectionProvider dir={dir}>
                  {children}
                  <Toaster richColors position="top-right" />
                </DirectionProvider>
              </NextIntlClientProvider>
            </UserProvider>
          </ReferenceDataProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
